name: Prepare release

on:
  workflow_call:
    inputs:
      release_tag:
        description: Name for the release tag
        required: false
        default: ''
        type: string
      cygport_file:
        description: Path to the cygport file
        required: true
        type: string
      bootstrap_packages:
        description: Cygwin packages required to parse the cygport file
        required: false
        type: string
        default: cygport
      publish:
        description: Publish the release or leave as a draft
        required: false
        type: boolean
        default: false
    outputs:
      release_tag:
        description: Name of the release tag
        value: ${{ jobs.prep-release.outputs.tag }}

permissions:
  contents: write

jobs:
  prep-release:
    name: Prepare release
    runs-on: windows-latest
    env:
      CYGPORT_FILE: ${{ inputs.cygport_file }}
      REQUESTED_TAG: ${{ inputs.release_tag }}
    outputs:
      tag: ${{ steps.tag-name.outputs.tag }}

    steps:

      - name: Configure Git for Windows' core.autocrlf
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Cygwin package cache
        uses: actions/cache/restore@v3
        with:
          key: cygwin-packages-${{ github.run_id }}-${{ github.run_attempt }}
          path: C:\cygwin-packages
          restore-keys: |
            cygwin-packages-${{ github.run_id }}-
            cygwin-packages-

      - name: Compute package cache checksum
        working-directory: C:\
        shell: bash
        run: |
          if [[ -d cygwin-packages ]]; then
            find cygwin-packages -type f ! -name setup.ini -print0 |
              sort -z |
              xargs -0 b2sum >cygwin-package-checksum.old
          fi

      - name: Install bootstrap packages
        id: install-bootstrap
        uses: cygwin/cygwin-install-action@db475590d56881c6cef7b3f96f6f3dd9532ea1f4
        with:
          packages: ${{ inputs.bootstrap_packages }}
          add-to-path: false

      - name: Load data from cygport file
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -e -o pipefail -o igncr {0}
        env:
          PATH: C:\cygwin\bin
        run: |
          vars_cmd=(cygport "$CYGPORT_FILE" vars NAME PVR PF ARCH)
          "${vars_cmd[@]}"
          eval "$("${vars_cmd[@]}")"
          printf 'CYGPORT_NAME=%s\n' "$NAME" | tee -a "$GITHUB_ENV"
          printf 'CYGPORT_PVR=%s\n' "$PVR" | tee -a "$GITHUB_ENV"
          printf 'CYGPORT_PF=%s\n' "$PF" | tee -a "$GITHUB_ENV"
          printf 'CYGPORT_ARCH=%s\n' "$ARCH" | tee -a "$GITHUB_ENV"

      - name: Check if package cache needs updating
        if: always() && steps.install-bootstrap.outcome == 'success'
        working-directory: C:\
        shell: bash
        run: |
          if [[ -d cygwin-packages ]]; then
            find cygwin-packages -type f ! -name setup.ini -print0 |
              sort -z |
              xargs -0 b2sum >cygwin-package-checksum.new
            if ! diff cygwin-package-checksum.old cygwin-package-checksum.new; then
              echo UPDATE_CYGWIN_PACKAGE_CACHE=YesPlease | tee -a "$GITHUB_ENV"
            fi
          fi

      - name: Store package cache
        if: always() && env.UPDATE_CYGWIN_PACKAGE_CACHE == 'YesPlease'
        uses: actions/cache/save@v3
        with:
          key: cygwin-packages-${{ github.run_id }}-${{ github.run_attempt }}
          path: C:\cygwin-packages

      - name: Generate cygcheck output
        if: always() && steps.install-bootstrap.outcome != 'skipped'
        run: C:\cygwin\bin\cygcheck.exe -srv >C:\cygwin\var\log\cygcheck.out

      - name: Store Cygwin logs
        if: always() && steps.install-bootstrap.outcome != 'skipped'
        uses: actions/upload-artifact@v3
        with:
          name: cygwin-logs
          path: C:\cygwin\var\log\

      - name: Get build cache
        id: build-cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ env.CYGPORT_NAME }}-build-${{ github.sha }}
          path: build-results.tar

      - name: Abort on cache miss
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          Write-Output "::error::Could not find build cache"
          exit 1

      - name: Check tag name
        id: tag-name
        run: |
          if ($Env:REQUESTED_TAG -eq "") {
            Write-Output "tag=v$Env:CYGPORT_PVR" | Tee-Object -FilePath $Env:GITHUB_OUTPUT
          } elseif ($Env:REQUESTED_TAG.StartsWith("v$Env:CYGPORT_PVR")) {
            Write-Output "tag=$Env:REQUESTED_TAG" | Tee-Object -FilePath $Env:GITHUB_OUTPUT
          } else {
            Write-Output "::error title=Bad tag::Requested tag $Env:REQUESTED_TAG not prefixed by v$Env:CYGPORT_PVR"
            exit 1
          }

      - name: Unpack the build
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -e -o pipefail -o igncr {0}
        env:
          PATH: C:\cygwin\bin
        run: tar -xf build-results.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag-name.outputs.tag }}
          draft: ${{ ! inputs.publish }}
          files: |
            ${{ env.CYGPORT_PF }}.${{ env.CYGPORT_ARCH }}/dist/${{ env.CYGPORT_NAME }}/*
            ${{ env.CYGPORT_PF }}.${{ env.CYGPORT_ARCH }}/dist/${{ env.CYGPORT_NAME }}/*/*
          fail_on_unmatched_files: true
          target_commitish: ${{ github.ref }}
          body: ${{ steps.tag-name.outputs.tag }}
